version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - darkatlas-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ahmed
      - POSTGRES_PASSWORD=password911
      - POSTGRES_DB=darkatlas
    ports:
      - "5432:5432"
    networks:
      - darkatlas-network

volumes:
  postgres_data:

networks:
  darkatlas-network:
    driver: bridge
